

const teamData = [
    {
      position: 'President',
      name: 'Nandini Parashar',
      image: 'https://res.cloudinary.com/duxmh9dws/image/upload/v1694319012/Nandini_wsvtlk.jpg',
      email: 'nandini087btece21@igdtuw.ac.in',
      instagram: 'https://www.instagram.com/nandini_parashar9/',
      phone: '8920729494',
      branch: 'ECE',
      year: '2',
      linkedin: 'https://www.linkedin.com/in/nandiniparashar9/',
      twitter: '',
    },
    {
      position: 'Secretary',
      name: 'Khushi Sharma',
      image: 'https://res.cloudinary.com/duxmh9dws/image/upload/v1694319012/Khushi_Sharma_pyqhxr.jpg',
      email: 'Khushi010btit21@igdtuw.ac.in',
      instagram: 'https://www.instagram.com/khushisharma_1309/',
      phone: '8745871331',
      branch: 'IT',
      year: '2',
      linkedin: 'https://www.linkedin.com/in/khushi-sharma-17185021b/',
      twitter: '',
    },
    {
      position: 'Treasurer',
      name: 'Kirti Sinha',
      image: 'https://res.cloudinary.com/duxmh9dws/image/upload/v1694319013/Kirti_Sinha_zdddk0.jpg',
      email: 'sinhakirti968@gmail.com',
      instagram: 'https://www.instagram.com/kirtisinha28/',
      phone: '7011778104',
      branch: 'CSE',
      year: '2',
      linkedin: 'http://linkedin.com/in/kirti-sinha-90b72b212/',
      twitter: '',
    },
    {
      position: 'Media Lead',
      name: 'Kashish Saini',
      image: 'https://res.cloudinary.com/duxmh9dws/image/upload/v1694319012/Kashish_tubtfo.jpg',
      email: 'sainikashish280304@gmail.com',
      instagram: 'https://instagram.com/kashish.saini28?igshid=Yjk4NWM2ZWVkMw==',
      phone: '8700898296',
      branch: 'ECE-AI',
      year: '2',
      linkedin: 'https://www.linkedin.com/in/kashish-saini-52363922b',
      twitter: '',
    },
    {
      position: 'PR lead',
      name: 'Palak Aggarwal',
      image: 'https://res.cloudinary.com/duxmh9dws/image/upload/v1694319013/Palak_Aggarwal_eq49dc.jpg',
      email: 'palakaggarwal009@gmail.com',
      instagram: 'https://www.instagram.com/palak.agg27/?igshid=ZDdkNTZiNTM%3D',
      phone: '8920607659',
      branch: 'CSAI',
      year: '2',
      linkedin: 'https://www.linkedin.com/in/palak-aggarwal-572a08229/',
      twitter: 'https://twitter.com/Kashish2803?t=dW62yed0F45d7P5pPNEIVA&s=09',
    },
    {
      position: 'EM lead',
      name: 'Khushi',
      image: 'https://res.cloudinary.com/duxmh9dws/image/upload/v1694319012/Khushi_eoyr9l.jpg',
      email: 'khushi018btece21@igdtuw.ac.in',
      instagram: 'https://www.instagram.com/__khushimittal/',
      phone: '9667938525',
      branch: 'ECE',
      year: '2',
      linkedin: 'https://www.linkedin.com/in/khushi-mittal-b63a86223',
      twitter: 'https://twitter.com/itszkhushi',
    },
    {
      position: 'WebD Lead',
      name: 'Kirti Aggarwal',
      image: 'https://res.cloudinary.com/duxmh9dws/image/upload/v1694319012/Kirti_Aggarwal_xrxn1o.jpg',
      email: 'kirti057btcse21@igdtuw.ac.in',
      instagram: 'https://www.instagram.com/kirti___2810/',
      phone: '9971791258',
      branch: 'CSE',
      year: '2',
      linkedin: 'https://www.linkedin.com/in/kirti-aggarwal-6b739522a/',
      twitter: 'https://twitter.com/KirtiAg2810',
    },
    {
      position: 'Media Manager',
      name: 'Shreya Joshi',
      image: 'https://res.cloudinary.com/duxmh9dws/image/upload/v1694319013/Shreya_Joshi_f25zcp.jpg',
      email: 'joshishreya2502@gmail.com',
      instagram: 'https://instagram.com/shreyyajoshii?igshid=NTc4MTIwNjQ2YQ==',
      phone: '8448773425',
      branch: 'ECE AI',
      year: '2',
      linkedin: 'https://www.linkedin.com/in/shreya-joshi-igdtuw/',
      twitter: 'https://twitter.com/shreyyajoshi?t=kfpPMFR6KCJmgFLyracHHQ&s=09',
    },

    // {
    //   position: 'temp',
    //   name: 'Megha Agarwal',
    //   image: '/images/Megha_Aggarwal.jpeg',
    //   email: 'megha081bteceai21@igdtuw.ac.in',
    //   instagram: '',
    //   phone: '9818472407',
    //   branch: 'ECEAI',
    //   year: '2',
    //   linkedin: 'www.linkedin.com/in/megha-agarwal-13150222b',
    //   twitter: '',
    // },
    {
      position: 'Content Lead',
      name: 'Diya Singla',
      image:'https://res.cloudinary.com/duxmh9dws/image/upload/v1694319012/Diya_nuhfmp.jpg',
      email: 'diya036btcsai21@igdtuw.ac.in',
      instagram: 'https://instagram.com/diya__singla?igshid=ZDc4ODBmNjlmNQ==',
      phone: '8929401833',
      branch: 'CSEAI',
      year: '2',
      linkedin: '',
      twitter: 'https://twitter.com/DiyaSingla15?t=Frl7Q-NeZwvRmhguPEBRDw&s=09',
    },  
  ];
  
  export default teamData;
  